# Generated by Django 6.0 on 2025-12-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_nurse_doctor_assigned_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='assigned_nurse',
        ),
        migrations.AddField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.nurse'),
        ),
    ]
