# Generated by Django 6.0 on 2025-12-27 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_doctor_assigned_nurse_appointment_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctor', to='hospital.nurse'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_sessions', to='hospital.nurse'),
        ),
    ]
